-- Supabase(PostgreSQL) 통합 회원 정보 테이블 생성 스크립트

-- 1. 기존 테이블이 존재할 경우 삭제 (초기화)
DROP TABLE IF EXISTS public.members CASCADE;

-- 2. 회원 테이블 생성 (통합 제약 조건 반영)
CREATE TABLE public.members (
    -- 1. number (기본키, 자동 증가 정수형)
    number BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 2. 아이디 (중복 불가능, 필수 입력)
    user_id VARCHAR(50) UNIQUE NOT NULL,
    
    -- 3. 비밀번호 (암호화된 문자열 저장, 필수 입력)
    password VARCHAR(255) NOT NULL,
    
    -- 4. 이름 (실명, 필수 입력)
    name VARCHAR(50) NOT NULL,
    
    -- 5. 닉네임 (게시판 표시용, 필수 입력)
    nickname VARCHAR(50) NOT NULL,
    
    -- 6. 이메일 (중복 불가능, 필수 입력)
    email VARCHAR(100) UNIQUE NOT NULL,
    
    -- 7. 전화번호 (선택 입력)
    phone VARCHAR(20),
    
    -- 8. 관리자 권한 여부 (기본값 false, 필수 입력)
    is_admin BOOLEAN DEFAULT false NOT NULL,
    
    -- 가입일시 및 정보 수정일시 (기본값 설정)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 테이블 설명 및 각 컬럼 주석 설정
COMMENT ON TABLE public.members IS '영진전문대학교 통합 회원 정보 테이블';
COMMENT ON COLUMN public.members.number IS '회원 고유 번호 (PK)';
COMMENT ON COLUMN public.members.user_id IS '로그인용 사용자 아이디';
COMMENT ON COLUMN public.members.password IS '암호화된 패스워드';
COMMENT ON COLUMN public.members.name IS '실명';
COMMENT ON COLUMN public.members.nickname IS '닉네임';
COMMENT ON COLUMN public.members.email IS '이메일 주소';
COMMENT ON COLUMN public.members.phone IS '연락처 번호 (선택)';
COMMENT ON COLUMN public.members.is_admin IS '관리자 여부';
COMMENT ON COLUMN public.members.created_at IS '최초 가입일시';
COMMENT ON COLUMN public.members.updated_at IS '정보수정일시';

-- 3. Row Level Security (RLS) 설정 활성화
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;

-- 4. 모든 사용자가 데이터를 삽입(회원가입)하고 조회(로그인)할 수 있는 보안 정책(Policy) 수립
CREATE POLICY "Enable insert for everyone (Sign up)" 
ON public.members 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Enable select for everyone (Login)" 
ON public.members 
FOR SELECT 
USING (true);

CREATE POLICY "Enable update for everyone" 
ON public.members 
FOR UPDATE 
USING (true) 
WITH CHECK (true);

CREATE POLICY "Enable delete for everyone" 
ON public.members 
FOR DELETE 
USING (true);

